spring.application.name=PARCHAFACE

spring.datasource.url=jdbc:mysql://localhost:3306/PARCHAFACE
spring.datasource.username=root
spring.datasource.password=D!**L&7z

server.port=${PORT:8080}


# =========================
# DATASOURCE
# =========================


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# SECURITY / LOGS
# =========================
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE

jwt.secret=${JWT_SECRET:YE3WfFDtfcNK8b1MeC2nwO+0TejGw+AtIOpkJX/Jzl8=}

# =========================
# MAIL (Gmail)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:datoquemado@gmail.com}
spring.mail.password=${MAIL_PASSWORD:yqox hpvs tpqw wzio}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# =========================
# GOOGLE
# =========================
google.client.id=${GOOGLE_CLIENT_ID:163443075503-daa2pefh4uf54vaj8n7av8k260rla20e.apps.googleusercontent.com}

# =========================
# MULTIPART
# =========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB


# CLOUDINARY
cloudinary.cloud-name=db6ykykid
cloudinary.api-key=531155144687711
cloudinary.api-secret=2qLY__-0HaBCe0SXWfzxBlh6PEI